#!/usr/bin/env python3
"""Generate the bambu-mcp section of the bambu-printer-manager documentation site.

Writes a static snapshot of this server's MCP tool reference and REST API reference as
Markdown pages under bpm's docs tree, where bpm's MkDocs build publishes them next to the
Client Container section. Nothing here touches a printer or starts a session.

Sources, all read live from this checkout:
  - MCP tools: a scratch FastMCP server fed by tools._registry.register_tools(), the same
    registration path the daemon uses (as test_tool_annotations.py does). server.py is never
    imported, so no log file, session or atexit hook is created.
  - REST API: api_server.build_openapi_document(api_server._build_app()), the document the
    running daemon serves at /api/openapi.json.
  - Overview: docs/site/overview.md, hand-written; its capabilities marker is filled in here.

Also refreshes the tool summary between the gen_docs markers in README.md.

Usage:
    .venv/bin/python3 gen_docs.py [OUT_DIR]

OUT_DIR defaults to ../bambu-printer-manager/docs/bambu-mcp. Every file in it is generated:
the directory is emptied of stale .md files first. Re-run after any tool, docstring, route or
overview change, then stage the pages in bambu-printer-manager.
"""

from __future__ import annotations

import asyncio
import inspect
import json
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from mcp.server.fastmcp import FastMCP  # noqa: E402

import api_server  # noqa: E402
from tools import _registry  # noqa: E402

DEFAULT_OUT = ROOT.parent / "bambu-printer-manager" / "docs" / "bambu-mcp"
REPO_URL = "https://github.com/synman/bambu-mcp"
OVERVIEW_SRC = ROOT / "docs" / "site" / "overview.md"
README = ROOT / "README.md"
CAPABILITIES_MARKER = "<!-- gen_docs:capabilities -->"
README_BEGIN = "<!-- gen_docs:tools:begin -->"
README_END = "<!-- gen_docs:tools:end -->"
SITE_URL = "https://synman.github.io/bambu-printer-manager/bambu-mcp/"
BANNER = (
    "<!-- Generated by bambu-mcp/gen_docs.py. Do not edit here: change the source in "
    "bambu-mcp and re-run the generator. -->"
)

# Page slug and heading for each tool module, in TOOL_MODULES order.
CATEGORIES = {
    "tools.state": ("state", "Printer State"),
    "tools.print_control": ("print-control", "Print Control"),
    "tools.climate": ("climate", "Climate"),
    "tools.filament": ("filament", "Filament & AMS"),
    "tools.nozzle": ("nozzle", "Nozzles"),
    "tools.detectors": ("detectors", "Detectors"),
    "tools.management": ("management", "Printer Management"),
    "tools.files": ("files", "Files"),
    "tools.system": ("system", "System"),
    "tools.discovery": ("discovery", "Discovery"),
    "tools.commands": ("commands", "Raw Commands"),
    "tools.camera": ("camera", "Camera"),
    "tools.notifications": ("notifications", "Alerts"),
    "tools.url_factory": ("snapshots", "Snapshots & Monitoring Data"),
    "tools.charts": ("charts", "Charts"),
}

SECTION_RE = re.compile(r"^(Args|Returns|Notes|Raises|Examples?):\s*$")
ARG_RE = re.compile(r"^(\w+)(?:\s*\([^)]*\))?:\s*(.*)$")
LABEL_RE = re.compile(r"^([A-Z][A-Za-z-]*(?: [A-Za-z-]+){0,3}):(?=\s)")
CODE_SPAN_RE = re.compile(r"(`+)(.+?)\1", re.S)
ALIGNED_RE = re.compile(r"\S {3,}\S")
BULLET_RE = re.compile(r"^[-*] ")


# ── Docstring to Markdown ────────────────────────────────────────────────────


def _escape(text: str) -> str:
    """Escape Markdown-active characters outside code spans.

    ``<`` would open an HTML tag and swallow text such as '<name>'; ``*``, ``~``, ``^`` and
    ``$`` would start emphasis, subscript, superscript or math under bpm's extensions.
    """
    out, pos = [], 0
    for m in CODE_SPAN_RE.finditer(text):
        out.append(_escape_plain(text[pos : m.start()]))
        out.append(m.group(0))
        pos = m.end()
    out.append(_escape_plain(text[pos:]))
    return "".join(out)


def _escape_plain(text: str) -> str:
    text = text.replace("\\", "\\\\").replace("<", "&lt;")
    for ch in "*~^$":
        text = text.replace(ch, "\\" + ch)
    return re.sub(r"(?m)^#", r"\\#", text)


def _outside_code(text: str) -> str:
    return CODE_SPAN_RE.sub("", text)


def _is_markdown_safe(lines: list[str]) -> bool:
    """True when a paragraph renders as intended once escaped.

    Prose at column 0 and flat ``- `` bullets whose continuation lines are indented a few
    spaces are safe. Deeper indentation (nested lists, aligned tables, code samples) and
    column-aligned text are not: Markdown would collapse or misread them.
    """
    in_bullet = False
    for line in lines:
        indent = len(line) - len(line.lstrip(" "))
        if BULLET_RE.match(line):
            in_bullet = True
        elif indent and not (in_bullet and indent <= 4):
            return False
    return not ALIGNED_RE.search(_outside_code("\n".join(lines)))


def _fence(lines: list[str]) -> str:
    body = "\n".join(lines).replace("```", "'''")
    return f'```{{ .text linenums="0" title="" }}\n{body}\n```'


def to_markdown(text: str, bold_labels: bool = False) -> str:
    """Convert one docstring block to Markdown, paragraph by paragraph."""
    paragraphs, cur = [], []
    for line in textwrap.dedent(text).splitlines():
        if line.strip():
            cur.append(line.rstrip())
        elif cur:
            paragraphs.append(cur)
            cur = []
    if cur:
        paragraphs.append(cur)

    out = []
    for para in paragraphs:
        para = textwrap.dedent("\n".join(para)).splitlines()
        if not _is_markdown_safe(para):
            out.append(_fence(para))
            continue
        lines, prev_bullet = [], None
        for line in para:
            bullet = bool(BULLET_RE.match(line))
            if bullet and prev_bullet is False:
                lines.append("")
            if not line.startswith(" "):
                prev_bullet = bullet
            lines.append(line)
        md = _escape("\n".join(lines))
        if bold_labels and not BULLET_RE.match(md):
            md = LABEL_RE.sub(r"**\1:**", md, count=1)
        out.append(md)
    return "\n\n".join(out)


def split_docstring(doc: str) -> tuple[str, dict[str, str]]:
    """Split a Google-style docstring into its lead text and named sections."""
    lead, sections, name = [], {}, None
    for line in inspect.cleandoc(doc or "").splitlines():
        m = SECTION_RE.match(line)
        if m:
            name = m.group(1)
            sections[name] = []
        elif name:
            sections[name].append(line)
        else:
            lead.append(line)
    return "\n".join(lead).strip(), {k: "\n".join(v) for k, v in sections.items()}


def parse_args(block: str) -> dict[str, str]:
    """Map each argument in an Args block to its description, joined onto one line."""
    args, name = {}, None
    for line in textwrap.dedent(block).splitlines():
        m = ARG_RE.match(line) if line and not line[0].isspace() else None
        if m:
            name = m.group(1)
            args[name] = m.group(2).strip()
        elif name and line.strip():
            args[name] = f"{args[name]} {line.strip()}".strip()
    return args


# ── Shared schema helpers ────────────────────────────────────────────────────


def schema_type(schema: dict) -> str:
    if "anyOf" in schema:
        return " or ".join(schema_type(s) for s in schema["anyOf"])
    if "enum" in schema:
        return "one of " + ", ".join(f"`{json.dumps(v)}`" for v in schema["enum"])
    kind = schema.get("type", "any")
    if kind == "array" and "items" in schema:
        return f"array of {schema_type(schema['items'])}"
    return kind


def param_line(name: str, schema: dict, required: bool, desc: str, where: str = "") -> str:
    facts = [schema_type(schema)]
    if where:
        facts.append(where)
    if required:
        facts.append("required")
    elif "default" in schema:
        facts.append(f"default `{json.dumps(schema['default'])}`")
    if "example" in schema:
        facts.append(f"example `{schema['example']}`")
    text = f"- `{name}` ({', '.join(facts)})"
    return f"{text}: {_escape(desc)}" if desc else text


# ── MCP tools ────────────────────────────────────────────────────────────────


def load_tools() -> list[dict]:
    mcp = FastMCP(name="bambu-mcp-docs")
    _registry.register_tools(mcp)
    listed = {t.name: t for t in asyncio.run(mcp.list_tools())}
    tools = []
    for fn in _registry.registered_tools():
        tool = listed[fn.__name__]
        slug, category = CATEGORIES[fn.__module__]
        ann = tool.annotations
        props = tool.inputSchema.get("properties", {})
        tools.append({
            "name": tool.name,
            "title": ann.title.removeprefix("Bambu: "),
            "read_only": ann.readOnlyHint,
            "destructive": ann.destructiveHint,
            "guarded": "user_permission" in props,
            "schema": tool.inputSchema,
            "doc": tool.description or "",
            "module": fn.__module__,
            "slug": slug,
            "category": category,
        })
    return tools


def access(tool: dict) -> str:
    if tool["read_only"]:
        return "read-only"
    return "write, destructive" if tool["destructive"] else "write"


def tool_section(tool: dict) -> str:
    lead, sections = split_docstring(tool["doc"])
    arg_docs = parse_args(sections.get("Args", ""))
    schema = tool["schema"]
    required = set(schema.get("required", []))

    facts = [f"**{_escape(tool['title'])}**", access(tool)]
    if tool["guarded"]:
        facts.append("needs `user_permission=True`")
    parts = [f"## {tool['name']}", " · ".join(facts), to_markdown(lead, bold_labels=True)]

    props = schema.get("properties", {})
    if props:
        parts.append("**Parameters**")
        parts.append("\n".join(
            param_line(n, s, n in required, arg_docs.get(n, "")) for n, s in props.items()
        ))
    else:
        parts.append("**Parameters:** none.")
    for name in ("Returns", "Raises", "Notes", "Example", "Examples"):
        if sections.get(name, "").strip():
            parts.append(f"**{name}**")
            parts.append(to_markdown(sections[name]))
    return "\n\n".join(parts)


def tool_pages(tools: list[dict]) -> dict[str, str]:
    pages, by_slug = {}, {}
    for tool in tools:
        by_slug.setdefault(tool["slug"], []).append(tool)
    for slug, group in by_slug.items():
        category, module = group[0]["category"], group[0]["module"]
        rows = "\n".join(
            f"| [`{t['name']}`](#{t['name']}) | {_escape(t['title'])} | {access(t)} |"
            for t in group
        )
        body = [
            BANNER,
            f"# {category}",
            f"{len(group)} tools, defined in "
            f"[`{module.replace('.', '/')}.py`]({REPO_URL}/blob/main/{module.replace('.', '/')}.py).",
            f"| Tool | Title | Access |\n|---|---|---|\n{rows}",
            *(tool_section(t) for t in group),
        ]
        pages[f"tools/{slug}.md"] = "\n\n".join(body) + "\n"
    return pages


def tools_index(tools: list[dict]) -> str:
    slugs = list(dict.fromkeys(t["slug"] for t in tools))
    cat_rows = []
    for slug in slugs:
        group = [t for t in tools if t["slug"] == slug]
        writes = sum(not t["read_only"] for t in group)
        cat_rows.append(f"| [{group[0]['category']}]({slug}.md) | {len(group)} | {writes} |")
    rows = "\n".join(
        f"| [`{t['name']}`]({t['slug']}.md#{t['name']}) | {_escape(t['title'])} | "
        f"{t['category']} | {access(t)} |"
        for t in sorted(tools, key=lambda t: t["name"])
    )
    guarded = sum(t["guarded"] for t in tools)
    return "\n\n".join([
        BANNER,
        "# MCP Tools",
        f"bambu-mcp registers {len(tools)} tools. Each carries MCP annotations: a title and a "
        "read-only flag, plus destructive, idempotent and open-world hints.",
        f"{guarded} of the {sum(not t['read_only'] for t in tools)} write tools refuse to act "
        "unless called with `user_permission=True`. Without it they change nothing and return a "
        "refusal naming the consequence. "
        + "The rest need no permission because they change only the local server, not the "
        "printer: " + ", ".join(
            f"`{t['name']}`" for t in tools if not t["read_only"] and not t["guarded"]) + ". Tools that disturb a print also refuse while the printer is "
        "printing, whatever `user_permission` says.",
        "Parameters, return shapes and notes below come from the tool docstrings the server "
        "sends to MCP clients.",
        "## By category",
        "| Category | Tools | Write tools |\n|---|---|---|\n" + "\n".join(cat_rows),
        "## All tools",
        "| Tool | Title | Category | Access |\n|---|---|---|---|\n" + rows,
    ]) + "\n"


# ── REST API ─────────────────────────────────────────────────────────────────


def load_openapi() -> dict:
    return api_server.build_openapi_document(api_server._build_app())


def rest_operations(doc: dict) -> list[dict]:
    """One entry per route, merging methods that share an operation id and description."""
    ops = []
    for path, methods in doc["paths"].items():
        merged: dict[tuple, dict] = {}
        for method, op in methods.items():
            key = (op.get("operationId"), op.get("description"))
            if key in merged:
                merged[key]["methods"].append(method.upper())
            else:
                merged[key] = {"path": path, "methods": [method.upper()], "op": op}
        ops.extend(merged.values())
    return ops


def rest_section(entry: dict) -> str:
    op, path = entry["op"], entry["path"]
    parts = [f"### {', '.join(entry['methods'])} {path}"]
    summary = op.get("summary", "").strip()
    desc = op.get("description", "").strip()
    if summary:
        parts.append(_escape(summary))
        if desc.startswith(summary):
            desc = desc[len(summary):].strip()
    if desc:
        parts.append(to_markdown(desc))

    params = op.get("parameters", [])
    if params:
        parts.append("**Parameters**")
        parts.append("\n".join(
            param_line(p["name"], p.get("schema", {}), p.get("required", False),
                       p.get("description", ""), p.get("in", ""))
            for p in params
        ))
    content = op.get("requestBody", {}).get("content", {})
    if content:
        kinds = " or ".join(f"`{k}`" for k in content)
        schema = next(iter(content.values())).get("schema", {})
        required = set(schema.get("required", []))
        parts.append(f"**Request body** ({kinds})")
        parts.append("\n".join(
            param_line(n, s, n in required, s.get("description", ""))
            for n, s in schema.get("properties", {}).items()
        ) or "Any.")

    responses = []
    for code, resp in op.get("responses", {}).items():
        line = f"- `{code}`: {_escape(resp.get('description', ''))}"
        for media in resp.get("content", {}).values():
            example = media.get("schema", {}).get("example")
            if example is not None:
                line += "\n\n    ```json\n" + textwrap.indent(
                    json.dumps(example, indent=2, ensure_ascii=False), "    ") + "\n    ```"
                break
        responses.append(line)
    if responses:
        parts.append("**Responses**")
        parts.append("\n".join(responses))
    return "\n\n".join(parts)


def rest_page(doc: dict) -> tuple[str, int]:
    ops = rest_operations(doc)
    tags = [t["name"] for t in doc.get("tags", [])]
    for entry in ops:
        for tag in entry["op"].get("tags", ["Other"]):
            if tag not in tags:
                tags.append(tag)
    groups = {tag: [e for e in ops if (e["op"].get("tags") or ["Other"])[0] == tag] for tag in tags}
    tag_desc = {t["name"]: t.get("description", "") for t in doc.get("tags", [])}
    method_count = sum(len(e["methods"]) for e in ops)

    parts = [
        BANNER,
        "# REST API Reference",
        f"The bambu-mcp daemon serves an HTTP API alongside MCP: {len(doc['paths'])} routes, "
        f"{method_count} route and method pairs. Every route acts on a printer through the "
        "same live session the MCP tools use.",
        "**Base URL:** `http://<host>:<api_port>/api`. The port is not fixed. It comes from a "
        "shared pool that starts at 49152. Discover it with the `get_server_info` MCP tool, "
        "or by probing `GET /api/server_info` from port 49152 upward.",
        "**Authentication:** none. The API listens on all network interfaces. Anyone who can "
        "reach the port can read printer state and send commands. Keep it on a trusted network "
        "or behind a firewall.",
        "**Printer selection:** most routes take a `printer` name. A ⚠️ at the start of a "
        "summary marks a write operation.",
        "**OpenAPI:** the running server publishes `GET /api/openapi.json` and a Swagger UI "
        "at `GET /api/docs`. This page is generated from that same document.",
        "## Contents",
        "\n".join(f"- [{t}](#{_slug(t)}) ({len(groups[t])})" for t in tags if groups[t]),
    ]
    for tag in tags:
        if not groups[tag]:
            continue
        parts.append(f"## {tag}")
        if tag_desc.get(tag):
            parts.append(_escape(tag_desc[tag]))
        for entry in groups[tag]:
            parts.append(rest_section(entry))
            parts.append("---")
    return "\n\n".join(parts) + "\n", len(doc["paths"])


def _slug(text: str) -> str:
    """Match MkDocs' default toc slug: lower case, drop punctuation, spaces to hyphens."""
    text = re.sub(r"[^\w\s-]", "", text.lower()).strip()
    return re.sub(r"[\s]+", "-", text)


# ── Overview, nav and README ─────────────────────────────────────────────────


def capabilities(tools: list[dict], route_count: int) -> str:
    read_only = sum(t["read_only"] for t in tools)
    guarded = sum(t["guarded"] for t in tools)
    return "\n".join([
        "| Surface | Count | Reference |",
        "|---|---|---|",
        f"| MCP tools | {len(tools)} ({read_only} read-only, {len(tools) - read_only} write, "
        f"{guarded} need `user_permission=True`) | [MCP Tools](tools/index.md) |",
        f"| REST API routes | {route_count} | [REST API](rest-api.md) |",
        "| MCP resources | 4 rules files plus 1 alert feed template | [Resources](#resources-and-prompt) |",
        "| MCP prompts | 1 (`bambu_system_context`) | [Resources](#resources-and-prompt) |",
    ])


def summary(tools: list[dict]) -> str:
    lines = ["* [Overview](index.md)", "* [MCP Tools](tools/index.md)"]
    for slug in dict.fromkeys(t["slug"] for t in tools):
        category = next(t["category"] for t in tools if t["slug"] == slug)
        lines.append(f"    * [{category}](tools/{slug}.md)")
    lines.append("* [REST API](rest-api.md)")
    return "\n".join(lines) + "\n"


def readme_block(tools: list[dict], route_count: int) -> str:
    rows = []
    for slug in dict.fromkeys(t["slug"] for t in tools):
        group = [t for t in tools if t["slug"] == slug]
        names = ", ".join(f"`{t['name']}`" for t in group)
        rows.append(f"| [{group[0]['category']}]({SITE_URL}tools/{slug}/) | {names} |")
    read_only = sum(t["read_only"] for t in tools)
    return "\n".join([
        README_BEGIN,
        f"{len(tools)} tools ({read_only} read-only, {len(tools) - read_only} write) and "
        f"{route_count} REST routes. Full reference: [bambu-mcp docs]({SITE_URL}).",
        "",
        "| Category | Tools |",
        "|---|---|",
        *rows,
        README_END,
    ])


def update_readme(block: str) -> bool:
    text = README.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(README_BEGIN) + ".*?" + re.escape(README_END), re.S)
    if not pattern.search(text):
        raise SystemExit(f"README.md has no {README_BEGIN} ... {README_END} block")
    new = pattern.sub(lambda _: block, text)
    if new != text:
        README.write_text(new, encoding="utf-8")
    return new != text


def main() -> None:
    out = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_OUT
    if not out.parent.is_dir():
        raise SystemExit(f"parent of output directory does not exist: {out.parent}")

    tools = load_tools()
    rest, route_count = rest_page(load_openapi())
    overview = OVERVIEW_SRC.read_text(encoding="utf-8")
    if CAPABILITIES_MARKER not in overview:
        raise SystemExit(f"{OVERVIEW_SRC} has no {CAPABILITIES_MARKER} line")

    pages = {
        "index.md": BANNER + "\n\n" + overview.replace(
            CAPABILITIES_MARKER, capabilities(tools, route_count)),
        "SUMMARY.md": summary(tools),
        "rest-api.md": rest,
        "tools/index.md": tools_index(tools),
        **tool_pages(tools),
    }

    for stale in out.rglob("*.md") if out.is_dir() else []:
        if stale.relative_to(out).as_posix() not in pages:
            stale.unlink()
    for rel, text in pages.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    readme_changed = update_readme(readme_block(tools, route_count))
    print(f"wrote {len(pages)} pages to {out}: {len(tools)} tools, {route_count} routes"
          f"{'; README.md updated' if readme_changed else ''}")


if __name__ == "__main__":
    main()
